name: Build Docker Image emby

on:
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * *'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Docker Image 构建环境
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.emby
          platforms: linux/arm/v7
          push: true
          tags: |
            shiyu1314/emby-crack:latest
