
name: Docker Images emby

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Marker version and time
      id: getVersion
      run: |
        sed -i "s@COMMIT_HASH@$(git rev-parse --short HEAD)@" rootfs/Aria2-Pro
        sed -i "s@DATE_TIME@$(date +"%Y/%m/%d %H:%M")@" rootfs/Aria2-Pro
        cat rootfs/Aria2-Pro
        echo "::set-output name=time::$(date +"%Y%m%d%H%M")"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm/v7
        file: emby
        context: .
        push: true
        tags: |
          shiyu1314/emby
